from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 704)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1929, 1200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("tekstura-s-produktami-pitaniya.jpg"))
        self.label.setObjectName("label")
        self.lineEdit_street = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_street.setGeometry(QtCore.QRect(20, 130, 421, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_street.setFont(font)
        self.lineEdit_street.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.lineEdit_street.setObjectName("lineEdit_street")
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        self.label_heading.setGeometry(QtCore.QRect(20, 50, 941, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_heading.setFont(font)
        self.label_heading.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.label_heading.setObjectName("label_heading")
        self.lineEdit_number = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_number.setGeometry(QtCore.QRect(442, 130, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit_number.setFont(font)
        self.lineEdit_number.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.lineEdit_number.setObjectName("lineEdit_number")
        self.pushButton_searchAddress = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchAddress.setGeometry(QtCore.QRect(794, 130, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_searchAddress.setFont(font)
        self.pushButton_searchAddress.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_searchAddress.setObjectName("pushButton_searchAddress")
        self.textEdit_shops = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_shops.setGeometry(QtCore.QRect(630, 210, 361, 241))
        self.textEdit_shops.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.textEdit_shops.setObjectName("textEdit_shops")
        self.listWidget_goods = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_goods.setGeometry(QtCore.QRect(25, 331, 401, 251))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_goods.setFont(font)
        self.listWidget_goods.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.listWidget_goods.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_goods.setObjectName("listWidget_goods")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_goods.addItem(item)
        self.label_pick = QtWidgets.QLabel(self.centralwidget)
        self.label_pick.setGeometry(QtCore.QRect(26, 262, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_pick.setFont(font)
        self.label_pick.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.label_pick.setObjectName("label_pick")
        self.pushButton_searchGoods = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_searchGoods.setGeometry(QtCore.QRect(24, 592, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_searchGoods.setFont(font)
        self.pushButton_searchGoods.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_searchGoods.setObjectName("pushButton_searchGoods")
        self.label_headResult = QtWidgets.QLabel(self.centralwidget)
        self.label_headResult.setGeometry(QtCore.QRect(436, 492, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_headResult.setFont(font)
        self.label_headResult.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.label_headResult.setObjectName("label_headResult")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(446, 542, 531, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_result.setFont(font)
        self.label_result.setStyleSheet("background-color: rgba(255, 255, 255, 225);")
        self.label_result.setObjectName("label_result")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_street.setPlaceholderText(_translate("MainWindow", "Введите вашу улицу"))
        self.label_heading.setText(_translate("MainWindow", "Найдите самый выгодный магазин для покупки в вашем районе!"))
        self.lineEdit_number.setPlaceholderText(_translate("MainWindow", "Введите номер дома"))
        self.pushButton_searchAddress.setText(_translate("MainWindow", "Поиск"))
        self.textEdit_shops.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; text-decoration: underline;\">Наши магазины-партнёры:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Шестёрочка&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Диски&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Компас&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Развилка&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Преданный&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Хорошо&quot;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">&quot;Наша&quot;</span></p></body></html>"))
        __sortingEnabled = self.listWidget_goods.isSortingEnabled()
        self.listWidget_goods.setSortingEnabled(False)
        item = self.listWidget_goods.item(0)
        item.setText(_translate("MainWindow", "хлеб"))
        item = self.listWidget_goods.item(1)
        item.setText(_translate("MainWindow", "сыр"))
        item = self.listWidget_goods.item(2)
        item.setText(_translate("MainWindow", "колбаса"))
        item = self.listWidget_goods.item(3)
        item.setText(_translate("MainWindow", "молоко"))
        item = self.listWidget_goods.item(4)
        item.setText(_translate("MainWindow", "помидоры"))
        item = self.listWidget_goods.item(5)
        item.setText(_translate("MainWindow", "огурцы"))
        item = self.listWidget_goods.item(6)
        item.setText(_translate("MainWindow", "говядина"))
        item = self.listWidget_goods.item(7)
        item.setText(_translate("MainWindow", "свинина"))
        self.listWidget_goods.setSortingEnabled(__sortingEnabled)
        self.label_pick.setText(_translate("MainWindow", "Выберите необходимые продукты:"))
        self.pushButton_searchGoods.setText(_translate("MainWindow", "Найти лучший вариант покупки"))
        self.label_headResult.setText(_translate("MainWindow", "Лучший магазин для покупок ваших товаров"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
